<template>
  <div class="headers-management">
    <el-card class="card-container">
      <template #header>
        <div class="card-header">
          <div>
            <h3>请求头管理</h3>
            <p class="subtitle">管理爬虫系统的 HTTP 请求头，提升数据抓取成功率</p>
          </div>
          <div class="header-actions">
            <el-button type="primary" @click="addHeader">添加请求头</el-button>
            <el-button type="success" @click="openAutoGenerateDialog">自动生成有效请求头</el-button>
            <el-button @click="refreshList">刷新</el-button>
            <el-button @click="batchImport">批量导入</el-button>
          </div>
        </div>
      </template>

      <el-form :inline="true" :model="queryParams" class="search-form">
        <el-form-item label="目标域名">
          <el-input v-model="queryParams.domain" placeholder="请输入目标域名" clearable />
        </el-form-item>
        <el-form-item label="状态">
          <el-select v-model="queryParams.status" placeholder="请选择状态" clearable>
            <el-option label="启用" value="enabled" />
            <el-option label="禁用" value="disabled" />
          </el-select>
        </el-form-item>
        <el-form-item>
          <el-button type="primary" @click="onQuery">查询</el-button>
          <el-button @click="resetQuery">重置</el-button>
        </el-form-item>
      </el-form>

      <div class="stats-row">
        <el-card class="stat-card">
          <div class="stat-title">总数</div>
          <div class="stat-value">{{ stats.total }}</div>
        </el-card>
        <el-card class="stat-card">
          <div class="stat-title">启用</div>
          <div class="stat-value">{{ stats.enabled }}</div>
        </el-card>
        <el-card class="stat-card">
          <div class="stat-title">禁用</div>
          <div class="stat-value">{{ stats.disabled }}</div>
        </el-card>
        <el-card class="stat-card">
          <div class="stat-title">成功率</div>
          <div class="stat-value">{{ stats.successRate }}%</div>
        </el-card>
        <el-card class="stat-card">
          <div class="stat-title">低质量Header</div>
          <div class="stat-value">{{ stats.lowQualityTotal }}</div>
        </el-card>
        <el-card class="stat-card">
          <div class="stat-title">绑定覆盖率</div>
          <div class="stat-value">{{ stats.bindingCoverageRate }}%</div>
        </el-card>
      </div>

      <div class="domain-toolbar">
        <div class="domain-title">域名容量视图</div>
        <div class="domain-actions">
          <el-input v-model="autoBindForm.dataSourceId" placeholder="数据源ID" style="width: 120px" />
          <el-input v-model="autoBindForm.domain" placeholder="域名(可选)" style="width: 180px" />
          <el-input-number v-model="autoBindForm.minBindings" :min="1" :max="10" size="small" controls-position="right" />
          <el-button size="small" @click="runAutoBind(true)">自动绑定预演</el-button>
          <el-button size="small" type="primary" @click="runAutoBind(false)">自动绑定执行</el-button>
        </div>
      </div>

      <el-table :data="domainStats" size="small" style="width: 100%; margin-bottom: 12px;">
        <el-table-column prop="domain" label="域名" min-width="220" />
        <el-table-column prop="enabled" label="可用Headers" width="120" />
        <el-table-column prop="low_quality" label="低质量" width="100" />
        <el-table-column prop="target" label="目标" width="90" />
        <el-table-column prop="gap" label="缺口" width="90">
          <template #default="scope">
            <el-tag :type="scope.row.gap > 0 ? 'danger' : 'success'">
              {{ scope.row.gap }}
            </el-tag>
          </template>
        </el-table-column>
      </el-table>

      <div class="batch-actions">
        <el-button size="small" type="primary" :disabled="selectedIds.length === 0" @click="batchEnable">批量启用</el-button>
        <el-button size="small" type="warning" :disabled="selectedIds.length === 0" @click="batchDisable">批量禁用</el-button>
        <el-button size="small" :disabled="selectedIds.length === 0" @click="batchTest">批量测试</el-button>
        <el-button size="small" type="danger" :disabled="selectedIds.length === 0" @click="batchRemove">批量删除</el-button>
        <el-button size="small" :disabled="selectedIds.length === 0" @click="openBindDialog()">批量绑定</el-button>
      </div>

      <el-table :data="headersList" style="width: 100%" v-loading="loading" @selection-change="onSelectionChange">
        <el-table-column type="selection" width="48" />
        <el-table-column prop="domain" label="目标域名" width="200" />
        <el-table-column prop="name" label="请求头名称" width="150" />
        <el-table-column prop="value" label="请求头值" width="250" show-tooltip-when-overflow />
        <el-table-column prop="type" label="类型" width="100">
          <template #default="scope">
            <el-tag :type="getTypeTagType(scope.row.type)">
              {{ scope.row.type }}
            </el-tag>
          </template>
        </el-table-column>
        <el-table-column prop="priority" label="优先级" width="100">
          <template #default="scope">
            <el-tag :type="getPriorityTagType(scope.row.priority)">
              {{ scope.row.priority }}
            </el-tag>
          </template>
        </el-table-column>
        <el-table-column prop="status" label="状态" width="100">
          <template #default="scope">
            <el-tag :type="getStatusTagType(scope.row.status)">
              {{ getStatusText(scope.row.status) }}
            </el-tag>
          </template>
        </el-table-column>
        <el-table-column prop="lastUsed" label="最后使用" width="150" />
        <el-table-column prop="usageCount" label="使用次数" width="100" />
        <el-table-column prop="successRate" label="成功率" width="100">
          <template #default="scope">
            <el-progress
              :percentage="scope.row.successRate"
              :color="getSuccessRateColor(scope.row.successRate)"
              :show-text="false"
              :stroke-width="20"
            />
            <span>{{ scope.row.successRate }}%</span>
          </template>
        </el-table-column>
        <el-table-column label="操作" width="250">
          <template #default="scope">
            <el-button size="small" @click="editHeader(scope.row)">编辑</el-button>
            <el-button size="small" type="danger" @click="deleteHeader(scope.row)">删除</el-button>
            <el-button
              size="small"
              :type="scope.row.status === 'enabled' ? 'info' : 'success'"
              @click="toggleStatus(scope.row)"
            >
              {{ scope.row.status === 'enabled' ? '禁用' : '启用' }}
            </el-button>
            <el-button size="small" @click="openBindDialog(scope.row)">绑定</el-button>
            <el-button size="small" @click="duplicateHeader(scope.row)">复制</el-button>
          </template>
        </el-table-column>
      </el-table>

      <el-pagination
        v-model:current-page="currentPage"
        v-model:page-size="pageSize"
        :page-sizes="[10, 20, 50, 100]"
        :background="true"
        layout="total, sizes, prev, pager, next, jumper"
        :total="total"
        style="margin-top: 20px; justify-content: center;"
        @size-change="handleSizeChange"
        @current-change="handleCurrentChange"
      />
    </el-card>

    <el-dialog :title="dialogTitle" v-model="dialogVisible" width="700px">
      <el-form ref="headerFormRef" :model="currentHeader" :rules="headerRules" label-width="120px">
        <el-form-item label="目标域名" prop="domain">
          <el-input v-model="currentHeader.domain" placeholder="请输入目标域名，如：example.com" />
        </el-form-item>
        <el-form-item label="请求头名称" prop="name">
          <el-input v-model="currentHeader.name" placeholder="请输入请求头名称，如：User-Agent" />
        </el-form-item>
        <el-form-item label="请求头值" prop="value">
          <el-input
            v-model="currentHeader.value"
            type="textarea"
            :rows="4"
            placeholder="请输入请求头值"
          />
        </el-form-item>
        <el-form-item label="类型">
          <el-select v-model="currentHeader.type" placeholder="请选择请求头类型">
            <el-option label="通用" value="common" />
            <el-option label="特定站点" value="specific" />
            <el-option label="移动端" value="mobile" />
            <el-option label="桌面端" value="desktop" />
          </el-select>
        </el-form-item>
        <el-form-item label="优先级">
          <el-select v-model="currentHeader.priority" placeholder="请选择优先级">
            <el-option label="高" value="high" />
            <el-option label="中" value="medium" />
            <el-option label="低" value="low" />
          </el-select>
        </el-form-item>
        <el-form-item label="状态">
          <el-switch
            v-model="currentHeader.status"
            :active-value="'enabled'"
            :inactive-value="'disabled'"
            active-text="启用"
            inactive-text="禁用"
          />
        </el-form-item>
        <el-form-item label="备注">
          <el-input
            v-model="currentHeader.remarks"
            type="textarea"
            :rows="3"
            placeholder="请输入备注信息"
          />
        </el-form-item>
      </el-form>
      <template #footer>
        <el-button @click="dialogVisible = false">取消</el-button>
        <el-button type="primary" @click="saveHeader">确定</el-button>
      </template>
    </el-dialog>

    <el-dialog title="自动生成有效请求头" v-model="autoGenerateVisible" width="820px">
      <el-form :model="autoGenerateForm" label-width="140px" class="auto-generate-form">
        <el-form-item label="目标域名">
          <el-input v-model="autoGenerateForm.domain" placeholder="例如：m.100qiu.com 或 https://m.100qiu.com" />
        </el-form-item>
        <el-form-item label="终端类型">
          <el-select v-model="autoGenerateForm.clientType">
            <el-option label="自动" value="auto" />
            <el-option label="移动端" value="mobile" />
            <el-option label="桌面端" value="desktop" />
          </el-select>
        </el-form-item>
        <el-form-item label="请求头类型">
          <el-select v-model="autoGenerateForm.type">
            <el-option label="通用" value="common" />
            <el-option label="特定站点" value="specific" />
            <el-option label="移动端" value="mobile" />
            <el-option label="桌面端" value="desktop" />
          </el-select>
        </el-form-item>
        <el-form-item label="优先级">
          <el-select v-model="autoGenerateForm.priority">
            <el-option label="高" value="high" />
            <el-option label="中" value="medium" />
            <el-option label="低" value="low" />
          </el-select>
        </el-form-item>
        <el-form-item label="Accept-Language">
          <el-input v-model="autoGenerateForm.acceptLanguage" placeholder="例如：zh-CN,zh;q=0.9,en;q=0.8" />
        </el-form-item>
        <el-form-item label="包含 Origin/Referer">
          <el-switch v-model="autoGenerateForm.includeOriginReferer" />
        </el-form-item>
        <el-form-item label="包含 Sec-Fetch 系列">
          <el-switch v-model="autoGenerateForm.includeSecFetch" />
        </el-form-item>
        <el-form-item label="生成后自动测试">
          <el-switch v-model="autoGenerateForm.autoTest" />
        </el-form-item>
      </el-form>

      <div class="auto-generate-actions">
        <el-button type="primary" plain @click="generateAutoHeadersPreview">生成预览</el-button>
        <span class="preview-count">预览条数：{{ autoGeneratedHeaders.length }}</span>
      </div>

      <el-table :data="autoGeneratedHeaders" size="small" max-height="260">
        <el-table-column prop="name" label="Header 名称" width="220" />
        <el-table-column prop="value" label="Header 值" show-tooltip-when-overflow />
      </el-table>

      <template #footer>
        <el-button @click="autoGenerateVisible = false">取消</el-button>
        <el-button type="primary" :disabled="autoGeneratedHeaders.length === 0" @click="saveAutoGeneratedHeaders">
          生成并保存
        </el-button>
      </template>
    </el-dialog>

    <el-dialog title="批量导入请求头" v-model="batchImportVisible" width="600px">
      <el-form :model="batchImportForm" label-width="100px">
        <el-form-item label="导入格式">
          <el-radio-group v-model="batchImportForm.format">
            <el-radio value="json">JSON格式</el-radio>
            <el-radio value="text">文本格式</el-radio>
            <el-radio value="csv">CSV格式</el-radio>
          </el-radio-group>
        </el-form-item>
        <el-form-item label="数据内容">
          <el-input
            v-model="batchImportForm.content"
            type="textarea"
            :rows="8"
            placeholder="请粘贴要导入的请求头数据..."
          />
        </el-form-item>
      </el-form>
      <template #footer>
        <el-button @click="batchImportVisible = false">取消</el-button>
        <el-button type="primary" @click="doBatchImport">导入</el-button>
      </template>
    </el-dialog>

    <el-dialog title="绑定请求头" v-model="bindDialogVisible" width="520px">
      <el-form :model="bindForm" label-width="110px">
        <el-form-item label="数据源ID">
          <el-input v-model="bindForm.dataSourceId" placeholder="可选，绑定到数据源" />
        </el-form-item>
        <el-form-item label="任务ID">
          <el-input v-model="bindForm.taskId" placeholder="可选，绑定到任务" />
        </el-form-item>
        <el-form-item label="优先级覆盖">
          <el-select v-model="bindForm.priorityOverride" placeholder="可选">
            <el-option label="高" :value="3" />
            <el-option label="中" :value="2" />
            <el-option label="低" :value="1" />
          </el-select>
        </el-form-item>
        <el-form-item label="启用">
          <el-switch v-model="bindForm.enabled" />
        </el-form-item>
      </el-form>
      <div class="binding-preview">
        <div class="binding-title">当前绑定预览</div>
        <div class="binding-section">
          <div class="binding-section-title">数据源绑定</div>
          <div v-if="bindingInfo.dataSourceBindings.length === 0" class="binding-empty">暂无</div>
          <div v-else class="binding-list">
            <div v-for="item in bindingInfo.dataSourceBindings" :key="`ds-${item.headerId}`">
              {{ item.header?.name }} ({{ item.header?.domain }})
            </div>
          </div>
        </div>
        <div class="binding-section">
          <div class="binding-section-title">任务绑定</div>
          <div v-if="bindingInfo.taskBindings.length === 0" class="binding-empty">暂无</div>
          <div v-else class="binding-list">
            <div v-for="item in bindingInfo.taskBindings" :key="`task-${item.headerId}`">
              {{ item.header?.name }} ({{ item.header?.domain }})
            </div>
          </div>
        </div>
      </div>
      <template #footer>
        <el-button @click="bindDialogVisible = false">取消</el-button>
        <el-button @click="loadBindings">加载绑定</el-button>
        <el-button type="primary" @click="confirmBind">绑定</el-button>
      </template>
    </el-dialog>
  </div>
</template>

<script setup>
import { ref, reactive, onMounted } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import {
  getHeadersList as getHeadersListApi,
  createHeader,
  updateHeader,
  deleteHeader as deleteHeaderApi,
  batchDeleteHeaders,
  batchTestHeaders,
  testHeader,
  getHeaderStats,
  importHeaders,
  bindHeadersToDataSource,
  bindHeadersToTask,
  getHeaderBindings,
  autoBindHeadersToDataSource
} from '@/api/headers'

const loading = ref(false)
const dialogVisible = ref(false)
const batchImportVisible = ref(false)
const bindDialogVisible = ref(false)
const autoGenerateVisible = ref(false)
const dialogTitle = ref('')
const currentPage = ref(1)
const pageSize = ref(10)
const total = ref(0)
const selectedIds = ref([])
const headerFormRef = ref()

const stats = reactive({
  total: 0,
  enabled: 0,
  disabled: 0,
  successRate: 100,
  lowQualityTotal: 0,
  bindingCoverageRate: 0
})
const domainStats = ref([])
const autoBindForm = reactive({
  dataSourceId: '',
  domain: '',
  minBindings: 3
})

const queryParams = reactive({
  domain: '',
  status: ''
})

const currentHeader = reactive({
  id: null,
  domain: '',
  name: '',
  value: '',
  type: 'common',
  priority: 'medium',
  status: 'enabled',
  lastUsed: '',
  usageCount: 0,
  successRate: 0,
  remarks: ''
})

const batchImportForm = reactive({
  format: 'json',
  content: ''
})

const bindForm = reactive({
  dataSourceId: '',
  taskId: '',
  priorityOverride: null,
  enabled: true,
  headerIds: []
})

const bindingInfo = reactive({
  dataSourceBindings: [],
  taskBindings: []
})

const headersList = ref([])
const autoGeneratedHeaders = ref([])

const desktopUaPool = [
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36',
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 14_7_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36',
  'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36'
]

const mobileUaPool = [
  'Mozilla/5.0 (Linux; Android 14; Pixel 8) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Mobile Safari/537.36',
  'Mozilla/5.0 (iPhone; CPU iPhone OS 18_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.3 Mobile/15E148 Safari/604.1',
  'Mozilla/5.0 (Linux; Android 13; SM-S9180) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Mobile Safari/537.36'
]

const autoGenerateForm = reactive({
  domain: '',
  clientType: 'auto',
  type: 'specific',
  priority: 'high',
  status: 'enabled',
  acceptLanguage: 'zh-CN,zh;q=0.9,en;q=0.8',
  includeOriginReferer: true,
  includeSecFetch: true,
  autoTest: false
})

const headerRules = {
  domain: [{ required: true, message: '请输入目标域名', trigger: 'blur' }],
  name: [{ required: true, message: '请输入请求头名称', trigger: 'blur' }],
  value: [{ required: true, message: '请输入请求头值', trigger: 'blur' }]
}

const getHeadersList = async () => {
  loading.value = true
  try {
    const res = await getHeadersListApi({
      page: currentPage.value,
      size: pageSize.value,
      ...queryParams
    })
    const data = res.data?.items || res.items || []
    headersList.value = data
    total.value = res.data?.total || res.total || 0
  } catch (error) {
    ElMessage.error('加载请求头列表失败')
    console.error('Error loading headers list:', error)
  } finally {
    loading.value = false
  }
}

const loadStats = async () => {
  try {
    const res = await getHeaderStats()
    const payload = res?.data || res || {}
    const data = payload?.data || payload || {}
    stats.total = data.total || 0
    stats.enabled = data.enabled || 0
    stats.disabled = data.disabled || 0
    const totalCount = data.total || 0
    stats.successRate = totalCount > 0 ? Math.round((data.enabled / totalCount) * 100) : 100
    stats.lowQualityTotal = Number(data.capacity?.low_quality_total || 0)
    const coverage = data.capacity?.bindings_coverage || {}
    stats.bindingCoverageRate = Number(coverage.coverage_rate || 0)
    domainStats.value = Array.isArray(data.domain_stats) ? data.domain_stats : []
  } catch (error) {
    console.error('Error loading header stats:', error)
  }
}

const onQuery = () => {
  currentPage.value = 1
  getHeadersList()
  loadStats()
}

const resetQuery = () => {
  queryParams.domain = ''
  queryParams.status = ''
  currentPage.value = 1
  getHeadersList()
  loadStats()
}

const onSelectionChange = (rows) => {
  selectedIds.value = rows.map((row) => row.id)
}

const batchEnable = async () => {
  try {
    await Promise.all(selectedIds.value.map((id) => updateHeader(id, { status: 'enabled' })))
    ElMessage.success('批量启用成功')
    getHeadersList()
    loadStats()
  } catch (error) {
    ElMessage.error('批量启用失败')
  }
}

const batchDisable = async () => {
  try {
    await Promise.all(selectedIds.value.map((id) => updateHeader(id, { status: 'disabled' })))
    ElMessage.success('批量禁用成功')
    getHeadersList()
    loadStats()
  } catch (error) {
    ElMessage.error('批量禁用失败')
  }
}

const batchTest = async () => {
  try {
    await batchTestHeaders({ ids: selectedIds.value })
    ElMessage.success('批量测试已提交')
    loadStats()
  } catch (error) {
    ElMessage.error('批量测试失败')
  }
}

const batchRemove = async () => {
  try {
    await ElMessageBox.confirm('确定删除选中的请求头吗？', '确认删除', {
      confirmButtonText: '确定',
      cancelButtonText: '取消',
      type: 'warning'
    })
    await batchDeleteHeaders({ ids: selectedIds.value })
    ElMessage.success('批量删除成功')
    getHeadersList()
    loadStats()
  } catch (error) {
    if (error !== 'cancel') {
      ElMessage.error('批量删除失败')
    }
  }
}

const openBindDialog = (row) => {
  bindForm.headerIds = row ? [row.id] : [...selectedIds.value]
  bindForm.dataSourceId = ''
  bindForm.taskId = ''
  bindForm.priorityOverride = null
  bindForm.enabled = true
  bindDialogVisible.value = true
}

const loadBindings = async () => {
  try {
    bindingInfo.dataSourceBindings = []
    bindingInfo.taskBindings = []
    if (bindForm.dataSourceId) {
      const res = await getHeaderBindings({ data_source_id: Number(bindForm.dataSourceId) })
      bindingInfo.dataSourceBindings = res.data?.dataSourceBindings || []
    }
    if (bindForm.taskId) {
      const res = await getHeaderBindings({ task_id: Number(bindForm.taskId) })
      bindingInfo.taskBindings = res.data?.taskBindings || []
    }
  } catch (error) {
    console.error('Error loading bindings:', error)
  }
}

const confirmBind = async () => {
  try {
    if (!bindForm.dataSourceId && !bindForm.taskId) {
      ElMessage.warning('请填写数据源ID或任务ID')
      return
    }

    if (bindForm.dataSourceId) {
      await bindHeadersToDataSource({
        dataSourceId: Number(bindForm.dataSourceId),
        headerIds: bindForm.headerIds,
        enabled: bindForm.enabled,
        priorityOverride: bindForm.priorityOverride
      })
    }

    if (bindForm.taskId) {
      await bindHeadersToTask({
        taskId: Number(bindForm.taskId),
        headerIds: bindForm.headerIds,
        enabled: bindForm.enabled,
        priorityOverride: bindForm.priorityOverride
      })
    }

    ElMessage.success('绑定成功')
    bindDialogVisible.value = false
  } catch (error) {
    ElMessage.error('绑定失败')
  }
}

const runAutoBind = async (dryRun = true) => {
  const dataSourceId = Number(autoBindForm.dataSourceId)
  if (!dataSourceId) {
    ElMessage.warning('请输入数据源ID')
    return
  }
  try {
    const res = await autoBindHeadersToDataSource({
      dataSourceId,
      domain: autoBindForm.domain || undefined,
      minBindings: Number(autoBindForm.minBindings || 3),
      dryRun,
    })
    const payload = res?.data || res || {}
    const data = payload?.data || payload || {}
    const selectedCount = Number(data.selected_count || 0)
    const boundCount = Number(data.bound_count || 0)
    ElMessage.success(
      dryRun
        ? `预演完成：可选 ${selectedCount}，预计新增绑定 ${boundCount}`
        : `执行完成：本次新增绑定 ${boundCount}`
    )
    await loadStats()
    if (!dryRun && bindForm.dataSourceId && Number(bindForm.dataSourceId) === dataSourceId) {
      await loadBindings()
    }
  } catch (error) {
    console.error(error)
    ElMessage.error(dryRun ? '自动绑定预演失败' : '自动绑定执行失败')
  }
}

const addHeader = () => {
  Object.assign(currentHeader, {
    id: null,
    domain: '',
    name: '',
    value: '',
    type: 'common',
    priority: 'medium',
    status: 'enabled',
    lastUsed: '',
    usageCount: 0,
    successRate: 0,
    remarks: ''
  })
  headerFormRef.value?.clearValidate()
  dialogTitle.value = '添加请求头'
  dialogVisible.value = true
}

const normalizeDomain = (input) => {
  const raw = String(input || '').trim()
  if (!raw) return ''
  try {
    const withProtocol = /^https?:\/\//i.test(raw) ? raw : `https://${raw}`
    const parsed = new URL(withProtocol)
    return parsed.host
  } catch {
    return raw.replace(/^https?:\/\//i, '').replace(/\/.*$/, '')
  }
}

const pickRandom = (arr) => arr[Math.floor(Math.random() * arr.length)]

const buildGeneratedHeaders = () => {
  const domain = normalizeDomain(autoGenerateForm.domain)
  const baseUrl = domain ? `https://${domain}` : ''
  const clientType = autoGenerateForm.clientType === 'auto'
    ? (Math.random() > 0.5 ? 'mobile' : 'desktop')
    : autoGenerateForm.clientType
  const ua = clientType === 'mobile' ? pickRandom(mobileUaPool) : pickRandom(desktopUaPool)

  const headers = [
    { name: 'User-Agent', value: ua },
    { name: 'Accept', value: 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8' },
    { name: 'Accept-Language', value: autoGenerateForm.acceptLanguage || 'zh-CN,zh;q=0.9,en;q=0.8' },
    { name: 'Accept-Encoding', value: 'gzip, deflate, br' },
    { name: 'Connection', value: 'keep-alive' },
    { name: 'Cache-Control', value: 'no-cache' },
    { name: 'Pragma', value: 'no-cache' },
    { name: 'Upgrade-Insecure-Requests', value: '1' }
  ]

  if (autoGenerateForm.includeOriginReferer && baseUrl) {
    headers.push({ name: 'Origin', value: baseUrl })
    headers.push({ name: 'Referer', value: `${baseUrl}/` })
  }

  if (autoGenerateForm.includeSecFetch) {
    headers.push({ name: 'Sec-Fetch-Site', value: 'same-origin' })
    headers.push({ name: 'Sec-Fetch-Mode', value: 'navigate' })
    headers.push({ name: 'Sec-Fetch-Dest', value: 'document' })
  }

  return headers
}

const openAutoGenerateDialog = () => {
  autoGenerateForm.domain = queryParams.domain || autoGenerateForm.domain
  autoGeneratedHeaders.value = []
  autoGenerateVisible.value = true
}

const generateAutoHeadersPreview = () => {
  const domain = normalizeDomain(autoGenerateForm.domain)
  if (!domain) {
    ElMessage.warning('请先输入目标域名')
    return
  }
  autoGeneratedHeaders.value = buildGeneratedHeaders()
  ElMessage.success(`已生成 ${autoGeneratedHeaders.value.length} 条有效请求头`)
}

const saveAutoGeneratedHeaders = async () => {
  const domain = normalizeDomain(autoGenerateForm.domain)
  if (!domain) {
    ElMessage.warning('请先输入目标域名')
    return
  }
  if (autoGeneratedHeaders.value.length === 0) {
    ElMessage.warning('请先生成预览')
    return
  }

  try {
    const createdIds = []
    for (const item of autoGeneratedHeaders.value) {
      const payload = {
        domain,
        name: item.name,
        value: item.value,
        type: autoGenerateForm.type,
        priority: autoGenerateForm.priority,
        status: autoGenerateForm.status,
        remarks: '程序自动生成'
      }
      const res = await createHeader(payload)
      const id = res?.data?.id || res?.id
      if (id) createdIds.push(id)
    }

    if (autoGenerateForm.autoTest && createdIds.length > 0) {
      await Promise.all(createdIds.map((id) => testHeader(id)))
    }

    ElMessage.success(`已生成并保存 ${autoGeneratedHeaders.value.length} 条请求头`)
    autoGenerateVisible.value = false
    getHeadersList()
    loadStats()
  } catch (error) {
    ElMessage.error('自动生成失败')
    console.error('Error auto generating headers:', error)
  }
}

const editHeader = (row) => {
  Object.assign(currentHeader, { ...row })
  headerFormRef.value?.clearValidate()
  dialogTitle.value = '编辑请求头'
  dialogVisible.value = true
}

const duplicateHeader = (row) => {
  const newRow = { ...row, id: null, lastUsed: '', usageCount: 0, successRate: 0 }
  Object.assign(currentHeader, newRow)
  headerFormRef.value?.clearValidate()
  dialogTitle.value = '复制请求头'
  dialogVisible.value = true
}

const saveHeader = async () => {
  try {
    if (!headerFormRef.value) return
    await headerFormRef.value.validate()

    const payload = {
      ...currentHeader,
      domain: currentHeader.domain.trim(),
      name: currentHeader.name.trim(),
      value: currentHeader.value.trim(),
      remarks: (currentHeader.remarks || '').trim()
    }

    if (currentHeader.id) {
      await updateHeader(currentHeader.id, payload)
      ElMessage.success('更新成功')
    } else {
      await createHeader(payload)
      ElMessage.success('创建成功')
    }

    dialogVisible.value = false
    getHeadersList()
    loadStats()
  } catch (error) {
    ElMessage.error(currentHeader.id ? '更新失败' : '创建失败')
    console.error('Error saving header:', error)
  }
}

const deleteHeader = async (row) => {
  try {
    await ElMessageBox.confirm(`确定要删除请求头 "${row.name}" 吗？`, '确认删除', {
      confirmButtonText: '确定',
      cancelButtonText: '取消',
      type: 'warning'
    })

    await deleteHeaderApi(row.id)
    ElMessage.success('删除成功')
    getHeadersList()
    loadStats()
  } catch (error) {
    if (error !== 'cancel') {
      ElMessage.error('删除失败')
      console.error('Error deleting header:', error)
    }
  }
}

const toggleStatus = async (row) => {
  try {
    const newStatus = row.status === 'enabled' ? 'disabled' : 'enabled'
    await updateHeader(row.id, { status: newStatus })
    row.status = newStatus
    ElMessage.success(`请求头${newStatus === 'enabled' ? '启用' : '禁用'}成功`)
    loadStats()
  } catch (error) {
    ElMessage.error('切换状态失败')
    console.error('Error toggling header status:', error)
  }
}

const batchImport = () => {
  batchImportForm.content = ''
  batchImportVisible.value = true
}

const doBatchImport = async () => {
  try {
    let importData
    try {
      if (batchImportForm.format === 'json') {
        importData = JSON.parse(batchImportForm.content)
      } else if (batchImportForm.format === 'text') {
        const lines = batchImportForm.content.split('\n').filter((line) => line.trim())
        importData = lines.map((line) => {
          const [domain, name, value, type = 'common', priority = 'medium'] = line.split('|')
          return { domain, name, value, type, priority, status: 'enabled' }
        })
      } else if (batchImportForm.format === 'csv') {
        const lines = batchImportForm.content.split('\n').filter((line) => line.trim())
        const headers = lines[0].split(',').map((h) => h.trim())
        importData = lines.slice(1).map((line) => {
          const values = line.split(',').map((v) => v.trim())
          const obj = {}
          headers.forEach((header, index) => {
            obj[header] = values[index] || ''
          })
          return obj
        })
      }
    } catch {
      ElMessage.error('数据格式错误，请检查输入内容')
      return
    }

    await importHeaders(importData)
    batchImportVisible.value = false
    ElMessage.success('批量导入成功')
    getHeadersList()
    loadStats()
  } catch (error) {
    ElMessage.error('批量导入失败')
    console.error('Error batch importing headers:', error)
  }
}

const refreshList = () => {
  getHeadersList()
  loadStats()
}

const handleSizeChange = (size) => {
  pageSize.value = size
  currentPage.value = 1
  getHeadersList()
  loadStats()
}

const handleCurrentChange = (page) => {
  currentPage.value = page
  getHeadersList()
  loadStats()
}

const getStatusText = (status) => {
  switch (status) {
    case 'enabled': return '启用'
    case 'disabled': return '禁用'
    default: return status
  }
}

const getStatusTagType = (status) => {
  switch (status) {
    case 'enabled': return 'success'
    case 'disabled': return 'info'
    default: return 'info'
  }
}

const getTypeTagType = (type) => {
  switch (type) {
    case 'common': return 'primary'
    case 'specific': return 'warning'
    case 'mobile': return 'success'
    case 'desktop': return 'danger'
    default: return 'info'
  }
}

const getPriorityTagType = (priority) => {
  switch (priority) {
    case 'high': return 'danger'
    case 'medium': return 'warning'
    case 'low': return 'info'
    default: return 'info'
  }
}

const getSuccessRateColor = (rate) => {
  if (rate >= 90) return '#67c23a'
  if (rate >= 70) return '#e6a23c'
  return '#f56c6c'
}

onMounted(() => {
  getHeadersList()
  loadStats()
})
</script>

<style scoped>
.card-container {
  margin: 20px;
}

.card-header {
  display: flex;
  justify-content: space-between;
  align-items: flex-start;
}

.card-header > div:first-child h3 {
  margin: 0 0 5px 0;
  font-size: 18px;
}

.subtitle {
  color: #909399;
  font-size: 14px;
  margin: 0;
}

.header-actions {
  display: flex;
  gap: 10px;
}

.search-form {
  margin-bottom: 20px;
}

.stats-row {
  display: grid;
  grid-template-columns: repeat(6, minmax(0, 1fr));
  gap: 12px;
  margin-bottom: 12px;
}

.stat-card {
  min-height: 96px;
}

.stat-title {
  color: #909399;
  font-size: 12px;
  margin-bottom: 6px;
}

.stat-value {
  font-size: 20px;
  font-weight: 600;
}

.batch-actions {
  display: flex;
  gap: 10px;
  margin-bottom: 12px;
}

.domain-toolbar {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 8px;
}

.domain-title {
  font-size: 13px;
  color: #606266;
  font-weight: 600;
}

.domain-actions {
  display: flex;
  align-items: center;
  gap: 8px;
}

.binding-preview {
  border-top: 1px solid #ebeef5;
  padding-top: 10px;
  margin-top: 10px;
}

.binding-title {
  font-weight: 600;
  margin-bottom: 8px;
}

.binding-section {
  margin-bottom: 8px;
}

.binding-section-title {
  color: #909399;
  font-size: 12px;
  margin-bottom: 4px;
}

.binding-empty {
  color: #c0c4cc;
  font-size: 12px;
}

.binding-list {
  font-size: 12px;
}

.auto-generate-form {
  margin-bottom: 12px;
}

.auto-generate-actions {
  display: flex;
  align-items: center;
  gap: 10px;
  margin-bottom: 10px;
}

.preview-count {
  font-size: 13px;
  color: #606266;
}

@media (max-width: 1440px) {
  .stats-row {
    grid-template-columns: repeat(3, minmax(0, 1fr));
  }
}
</style>
