export const DATA_CENTER_TEXT = {
  breadcrumbHome: '首页',
  breadcrumbDataSource: '数据源管理',
  breadcrumbDataCenter: '数据资产中心',

  pageTitle: '数据资产中心',
  pageSubtitle: '统一查看多源数据质量、分布与实时状态',
  refreshData: '刷新数据',
  exportData: '导出数据',

  statTotalMatches: '比赛总数',
  statActiveSources: '活跃数据源',
  statDataQuality: '数据质量',
  statErrorRate: '错误率',
  statAvgResponse: '平均响应',
  statStorageUsed: '存储占用',

  filterDataType: '数据类型',
  filterSource: '来源',
  filterDateRange: '时间范围',
  filterStatus: '状态',

  placeholderSelectDataType: '请选择数据类型',
  placeholderSelectSource: '请选择来源',
  placeholderSelectStatus: '请选择状态',

  optionMatchData: '比赛数据',
  optionOddsData: '赔率数据',
  optionEventData: '事件数据',
  optionStatData: '统计数据',

  rangeSeparator: '至',
  startDate: '开始日期',
  endDate: '结束日期',

  statusNormal: '正常',
  statusWarning: '告警',
  statusError: '异常',

  search: '查询',
  reset: '重置',

  viewTable: '表格',
  viewChart: '图表',
  viewDashboard: '仪表盘',
  chart: '图表',
  heatmap: '热力图',

  columnType: '类型',
  columnSource: '来源',
  columnTitle: '标题',
  columnStatus: '状态',
  columnQuality: '质量',
  columnRecordCount: '记录数',
  columnCreatedAt: '创建时间',
  columnUpdatedAt: '更新时间',
  columnActions: '操作',

  actionDetail: '详情',
  actionOdds: '赔率',
  actionMore: '更多',
  actionAnalyze: '分析',
  actionExportItem: '导出',
  actionRefresh: '刷新',
  actionDelete: '删除',

  realtimeStatsTitle: '实时状态',
  realtimeCurrentSpeed: '当前速度',
  realtimeQueueLength: '队列长度',
  realtimeSuccessRate: '成功率',
  realtimeActiveConnections: '活跃连接',

  drawerDataDetail: '数据详情',
  drawerOddsDetail: '赔率详情',

  exportDialogTitle: '导出设置',
  exportFormat: '导出格式',
  exportScope: '导出范围',
  exportCurrentPage: '当前页',
  exportSelectedPage: '已勾选',
  exportAllData: '全部',
  exportDateRange: '导出时间范围',
  cancel: '取消',
  confirmExport: '确认导出',

  sourceOfficial: '官方数据',
  sourceCrawler: '爬虫数据',
  sourcePrefix: '数据源',
  sourceUnknown: '未知来源',

  toastLoadStatsFailed: '加载统计数据失败',
  toastLoadDataFailed: '加载列表数据失败',
  toastDataRefreshed: '数据已刷新',
  toastExportCreating: '正在生成导出文件...',
  toastExportCreated: '导出任务已创建',
  toastExportFailed: '导出失败',
  toastOpenAnalyze: '已打开分析视图',
  toastExportSingle: '单条导出已触发',
  toastRefreshSubmitted: '刷新任务已提交',
  toastDeleteSuccess: '删除成功',

  confirmRefreshQuestionStart: '确认刷新 ',
  confirmRefreshQuestionEnd: ' 吗？',
  confirmRefreshTitle: '刷新确认',
  confirmDeleteQuestionStart: '确认删除 ',
  confirmDeleteQuestionEnd: ' 吗？此操作不可恢复。',
  confirmDeleteTitle: '删除确认',

  chartTrendTitle: '近7天趋势',
  chartLegendMatches: '比赛',
  chartLegendOdds: '赔率',
  chartLegendSp: 'SP',
  chartPieTitle: '来源分布',
  chartPieNoData: '暂无数据',
  chartQualityTitle: '质量分布',
  chartRealtimeTitle: '实时吞吐',
  chartRealtimeSpeed: '速度',

  typeTextMap: {
    matches: '比赛',
    odds: '赔率',
    events: '事件',
    statistics: '统计'
  },
  statusTextMap: {
    normal: '正常',
    warning: '告警',
    error: '异常'
  },

  mappingHealthTitle: '实体映射健康',
  mappingSyncStatus: '同步状态',
  mappingPendingConflicts: '待审冲突',
  mappingTotalConflicts: '总冲突数',
  mappingLastSyncCompleted: '最近同步完成',
  mappingLastSync: '最近同步',
  mappingLastFailureTime: '最近失败时间',
  mappingLastFailure: '最近失败',
  mappingError: '错误信息',
  mappingErrorNone: '无',
  mappingSyncStatusUnknown: '未知',
  mappingSyncStatusNotRun: '未执行',
  mappingSyncStatusRunning: '运行中',
  mappingSyncStatusSuccess: '成功',
  mappingSyncStatusFailed: '失败',
  mappingSyncStatusLoadFailed: '加载失败'
}

export const SYSTEM_MONITOR_TEXT = {
  pageTitle: '系统监控',
  refreshData: '刷新数据',
  enableAutoRefresh: '开启自动刷新',
  disableAutoRefresh: '停止自动刷新',
  autoRefreshEnabled: '已开启自动刷新',
  autoRefreshDisabled: '已停止自动刷新',

  healthCardSystem: '系统健康度',
  healthCardSuccessRate: '采集成功率',
  healthCardDataQuality: '数据质量',
  healthCardPerformance: '响应性能',

  statusHealthy: '健康',
  statusAbnormal: '异常',
  statusNormal: '正常',
  statusFluctuate: '波动',
  statusExcellent: '优秀',
  statusGeneral: '一般',
  statusGood: '良好',
  statusAttention: '关注',

  sectionTaskOverview: '任务执行概览',
  sectionMappingSync: '实体映射同步状态',
  sectionRealtimeAlert: '实时告警',
  sectionSystemResource: '系统资源监控',

  kvTotalTasks: '总任务数',
  kvRunningTasks: '运行中任务',
  kvRecentExecutions: '近期执行数',
  kvSuccessRate: '成功率',

  kvCurrentStatus: '当前状态',
  kvPendingConflicts: '待审冲突',
  kvTotalConflicts: '冲突总数',
  kvSuccessRate7d: '7天成功率',
  kvLastFinishedAt: '最近完成',
  kvLastError: '最近错误',

  tableTask: '任务',
  tableStatus: '状态',
  tableProgress: '进度',
  tableLevel: '级别',
  tableMetric: '指标',
  tableMessage: '告警信息',
  tableSource: '来源',
  tableTriggeredAt: '触发时间',
  tableActions: '操作',

  sourceMappingSync: '映射同步',
  sourceSystemMonitor: '系统监控',

  actionAcknowledge: '确认',
  actionDetail: '详情',

  resourceCpu: 'CPU使用率',
  resourceMemory: '内存使用率',
  resourceDisk: '磁盘使用率',
  resourceDbConn: '数据库连接',
  resourceDbConnUnit: '个',

  statusLoading: '加载中',
  statusRunning: '运行中',
  statusFailed: '失败',
  statusSuccess: '成功',
  statusNotRun: '未执行',

  taskStatusRunning: '运行中',
  taskStatusSuccess: '成功',
  taskStatusFailed: '失败',
  taskStatusPending: '待执行',
  taskFallbackNamePrefix: '任务#',

  alertCritical: '严重',
  alertWarning: '警告',
  alertInfo: '信息',

  alertMetricSyncFailed: '实体映射同步失败',
  alertMetricPendingConflicts: '实体映射待审冲突',
  alertMessageSyncFailedDefault: '最近一次映射同步失败',
  alertMessagePendingConflictsPrefix: '待审冲突数：',

  toastRefreshDone: '数据刷新完成',
  toastMappingAlertHint: '映射告警需在实体映射管理页处理',
  toastAlertAckSuccess: '告警已确认',
  toastAlertAckFailed: '确认告警失败'
}
