param(
  [Parameter(Mandatory = $true)][string]$Domain,
  [Parameter(Mandatory = $true)][string]$CertbotEmail,
  [string]$OutputPath = "",
  [string]$PostgresDb = "sport_lottery",
  [string]$PostgresUser = "postgres",
  [string]$PostgresPassword = "",
  [string]$SecretKey = "",
  [string]$CorsOrigins = "",
  [switch]$Force
)

$ErrorActionPreference = "Stop"

function Fill-RandomBytes([byte[]]$Bytes) {
  $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
  try {
    $rng.GetBytes($Bytes)
  } finally {
    $rng.Dispose()
  }
}

function New-RandomAlphaNumeric([int]$Length) {
  $chars = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789".ToCharArray()
  $buffer = New-Object char[] $Length
  $bytes = New-Object byte[] $Length
  Fill-RandomBytes -Bytes $bytes
  for ($i = 0; $i -lt $Length; $i++) {
    $buffer[$i] = $chars[$bytes[$i] % $chars.Length]
  }
  return -join $buffer
}

function New-HexSecret([int]$ByteLength) {
  $bytes = New-Object byte[] $ByteLength
  Fill-RandomBytes -Bytes $bytes
  return ([System.BitConverter]::ToString($bytes)).Replace("-", "").ToLowerInvariant()
}

$projectRoot = (Resolve-Path (Join-Path $PSScriptRoot "..\..")).Path
if ([string]::IsNullOrWhiteSpace($OutputPath)) {
  $OutputPath = Join-Path $projectRoot ".env.release"
}

if ((Test-Path $OutputPath) -and -not $Force) {
  throw "Release env file already exists: $OutputPath (use -Force to overwrite)"
}

if ([string]::IsNullOrWhiteSpace($PostgresPassword)) {
  $PostgresPassword = New-RandomAlphaNumeric -Length 32
}

if ([string]::IsNullOrWhiteSpace($SecretKey)) {
  $SecretKey = New-HexSecret -ByteLength 32
}

if ([string]::IsNullOrWhiteSpace($CorsOrigins)) {
  $CorsOrigins = "https://$Domain,https://www.$Domain"
}

$databaseUrl = "postgresql://${PostgresUser}:$PostgresPassword@postgres:5432/$PostgresDb"
$asyncDatabaseUrl = "postgresql+asyncpg://${PostgresUser}:$PostgresPassword@postgres:5432/$PostgresDb"

$outputDir = Split-Path -Parent $OutputPath
if (-not [string]::IsNullOrWhiteSpace($outputDir) -and -not (Test-Path $outputDir)) {
  New-Item -ItemType Directory -Force -Path $outputDir | Out-Null
}

$lines = @(
  "# Generated by scripts/deploy/init-release-env.ps1 on $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')",
  "DOMAIN=$Domain",
  "CERTBOT_EMAIL=$CertbotEmail",
  "",
  "ENVIRONMENT=production",
  "DEBUG=false",
  "",
  "POSTGRES_DB=$PostgresDb",
  "POSTGRES_USER=$PostgresUser",
  "POSTGRES_PASSWORD=$PostgresPassword",
  "",
  "DATABASE_URL=$databaseUrl",
  "ASYNC_DATABASE_URL=$asyncDatabaseUrl",
  "",
  "REDIS_URL=redis://redis:6379/0",
  "SECRET_KEY=$SecretKey",
  "",
  "CORS_ORIGINS=$CorsOrigins",
  "ALLOWED_ORIGINS=$CorsOrigins"
)

Set-Content -Path $OutputPath -Value $lines -Encoding ascii
Write-Host "[done] Release env file generated: $OutputPath"
