import sqlite3
conn = sqlite3.connect('sport_lottery.db')
c = conn.cursor()
c.execute("SELECT * FROM users WHERE username='admin'")
row = c.fetchone()
print("Admin用户数据:")
print(f"ID: {row[0]}")
print(f"用户名: {row[1]}")
print(f"邮箱: {row[2]}")
print(f"密码哈希: {row[3][:60]}...")
print(f"first_name: {row[4]}")
print(f"last_name: {row[5]}")
print(f"nickname: {row[6]}")
print(f"bio: {row[7]}")
print(f"avatar_url: {row[8]}")
print(f"phone: {row[9]}")
print(f"country: {row[10]}")
print(f"city: {row[11]}")
print(f"role: {row[12]}")
print(f"status: {row[13]}")
print(f"is_verified: {row[14]}")
print(f"is_online: {row[15]}")
print(f"user_type: {row[16]}")
print(f"timezone: {row[17]}")
print(f"language: {row[18]}")
print(f"notification_preferences: {row[19]}")
print(f"login_count: {row[20]}")
print(f"last_login_at: {row[21]}")
print(f"last_activity_at: {row[22]}")
print(f"followers_count: {row[23]}")
print(f"following_count: {row[24]}")
print(f"external_id: {row[25]}")
print(f"external_source: {row[26]}")
print(f"config: {row[27]}")
print(f"created_at: {row[28]}")
print(f"updated_at: {row[29]}")
print(f"created_by: {row[30]}")
print(f"updated_by: {row[31]}")
print(f"deleted_by: {row[32]}")
conn.close()